def e(f, i):
    try:
        return f()
    except Exception as e:
        traceback.print_exc()
        input(f'Error on {i}...')

